### ISSUE TITLE
Explain how to add nixos-scripts to configuration.nix

### ISSUE THREAD

**Issue by chadjoan** [matthiasbeyer/nixos-scripts#28]
I did a ``nix-env -qa ".*nix.*"`` and didn't find these scripts mentioned anywhere, so I assume these aren't packaged in the nixos channel.  Because of that, it'd be helpful if you could explain (probably in the readme.md) how to add nixos-scripts to my configuration.nix declarations so that it does not become forgotten.

Thank you!

**Comment by matthiasbeyer** [comment]
Hi!

No, nixos-scripts is not yet packaged. I'm planning some more improvements for the scripts and then I will release a `v0.1` or something. Until then I will not include a package, but the first release will be packaged for nixos!

I'm not sure you can actually add a package def to your `configuration.nix`, because there is no install script or whatever. All this stuff will be there in v0.1!

**Comment by chadjoan** [comment]
OK, thanks for explaining.  Good luck!
